[workspace]
authors = ["Yehuda Bernáth <yehudamber@gmail.com>"]
channels = ["conda-forge"]
name = "hello-pixi"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[dependencies]
cmake = "4.3.*"
ninja = "1.13.*"

clangxx = "22.*"
clang-tools = "22.*"

[target.linux-64.dependencies]
gxx = "16.*"
libcxx-devel = "22.*"

[target.win-64.dependencies]
vs2026_win-64 = "19.*"
