name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{ matrix.preset }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            env: default
            preset: linux-gcc-release
          - os: ubuntu-latest
            env: default
            preset: linux-clang-libstdcxx-release
          - os: ubuntu-latest
            env: default
            preset: linux-clang-libcxx-release
          - os: windows-latest
            env: msvc
            preset: windows-msvc-release
          - os: windows-latest
            env: default
            preset: windows-clang-release

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi Environment
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          environments: ${{ matrix.env }}
          frozen: true

      - name: Configure
        run: pixi run -e ${{ matrix.env }} cmake --preset ${{ matrix.preset }}

      - name: Build
        run: pixi run -e ${{ matrix.env }} cmake --build --preset ${{ matrix.preset }}

      - name: Test
        run: pixi run -e ${{ matrix.env }} ctest --preset ${{ matrix.preset }}
